Letux: rootfs: swap-on: take MB as parameter; check if size already set; use a swapfile.tmp for hot changes on devices with limited RAM
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/Letux/root/swap-on b/Letux/root/swap-on
--- a/Letux/root/swap-on
+++ b/Letux/root/swap-on
@@ -2,14 +2,13 @@
 
 SWAPFILE=/swapfile
 BOOTABLE=false
-MODE=2
 
 while [ "$1" ]
 do
 	case "$1" in
 		-r )
-			swapoff -a
-			sed -i.bak '/swapfile/d' /etc/fstab
+			swapoff $SWAPFILE
+			sed -i.bak "$SWAPFILE swap/d" /etc/fstab
 			echo "### $SWAPFILE deactivated."
 			exit
 			;;
@@ -18,7 +17,7 @@ do
 			BOOTABLE=true
 			;;
 		-* )
-			echo "usage: $0 [-br] [size in GB]"
+			echo "usage: $0 [-br] [size in MiB]"
 			exit
 			;;
 		*)
@@ -26,42 +25,76 @@ do
 	esac
 done
 
-# FIXME: specifying an explicit GB size should create/resize the swap file
+# FIXME: specifying an explicit MiB size should always create/resize the swap file
+# well, then we can't detect that it has not been changed!
 
-GB="$1"
-# [ "$GB" ] || GB=$(ls -l --block-size=1G $SWAPFILE 2>/dev/null | cut -d ' ' -f 5)	# same as currently
-[ "$GB" ] || GB=1
+CURRENTSIZE=$(swapon | grep  "^$SWAPFILE " | cut -d ' ' -f 3)	# has an M suffix
+[ "$CURRENTSIZE" ] || CURRENTSIZE=0
 
-echo "### setting up ${GB}GB swap on $SWAPFILE"
-swapoff -a
+SIZE="$1"
+[ "$SIZE" ] || SIZE=${CURRENTSIZE%M}
 
-if [ ! -r "$SWAPFILE" ]
+if [ "$SIZE" -eq "${CURRENTSIZE%M}" ]
 then
-	echo "### creating $SWAPFILE with ${GB}GB"
-	case "$MODE" in
-	0 )
-		# modern kernel syscall may not be compatible with older Debian
-		# fallocate: fallocate failed: Operation not supported
-		fallocate -l ${GB}GiB $SWAPFILE || exit
-		;;
-	1 )
-		# creates holes
-		# swapon: /swapfile: skipping - it appears to have holes.
-		truncate -s $( echo | awk "{print int(($GB) * 1024 * 1024 * 1024)}") /swapfile || exit
-		;;
-	2 )
-		[ "$GB" ] && rm -rf "$SWAPFILE"	# will resize
-		# only this works reliably although slowly
-		# the awk formula allows to specify e.g. 0.1 GB because it does a floating point calculation
-		dd if=/dev/zero of="$SWAPFILE" bs=1024 count=$( echo | awk "{print int(($GB) * 1048576)}") || exit
-		;;
-	esac
+	echo "### $SWAPFILE with ${SIZE}MiB already active, nothing to do"
+	exit 0
+fi
+
+if [ $(fgrep MemTotal: /proc/meminfo | ( read MEMTOTAL SIZE kB; echo $SIZE )) -lt 256000 ]
+then
+	echo "### we have less than 256MiB physical RAM. We can't turn off swap while e.g. running apt-get. So use a temp swap"
+	TMPSIZE=100
+fi
+
+if [ "$TMPSIZE" ]
+then
+
+	echo "### setting up ${TMPSIZE}MiB temporary swap on $SWAPFILE.tmp"
+	echo "   ... fallocate may fail, then we do a dd"
+	if ! fallocate -l $TMPSIZE $SWAPFILE.tmp
+	then	# fall back
+		echo "### creating $SWAPFILE.tmp with ${TMPSIZE}MiB"
+		COUNT=$( echo | awk "{print int(($TMPSIZE) * 1024)}")
+		dd if=/dev/zero of="$SWAPFILE.tmp" bs=1024 count=$COUNT || exit
+	fi
+	chmod 0600 "$SWAPFILE.tmp"
+	mkswap "$SWAPFILE.tmp"
+	swapon "$SWAPFILE.tmp"
+	# NOTE: if we fail here before the $SWAPFILE is installed we can't run again...
+	echo "### $SWAPFILE.tmp is set up."
+
+fi
+
+echo "### deactivate $SWAPFILE"
+swapoff $SWAPFILE
+
+echo "### setting up ${SIZE}MiB swap on $SWAPFILE"
+
+# modern kernel syscall may not be compatible with older Debian
+# fallocate: fallocate failed: Operation not supported
+echo "   ... fallocate may fail, then we do a dd"
+
+if ! fallocate -l $SIZE $SWAPFILE
+then
+	echo "### creating $SWAPFILE with ${SIZE}MiB"
+	# only this works reliably although slowly
+	COUNT=$( echo | awk "{print int(($SIZE) * 1024.0)}")
+	# echo count: $COUNT
+	dd if=/dev/zero of="$SWAPFILE" bs=1024 count=$COUNT || exit
 fi
 
 chmod 0600 "$SWAPFILE"
 mkswap "$SWAPFILE"
 swapon "$SWAPFILE"
 echo "### $SWAPFILE is set up."
+
+if [ "$TMPSIZE" ]
+then
+	echo "### deactivate and delete $SWAPFILE.tmp"
+	# NOTE: if we fail before before here, we can't run again...
+	swapoff $SWAPFILE.tmp
+	rm -f $SWAPFILE.tmp
+fi
 
 if $BOOTABLE
 then
